version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: employee_payroll_db
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: employee_payroll
    ports:
      - "5433:5432" # Exposes the DB to your local machine
    volumes:
      - dev_db_data:/var/lib/postgresql/data

volumes:
  dev_db_data:
